#encoding=utf-8

import xml.dom.minidom
import codecs

doc = xml.dom.minidom.Document()
root = doc.createElement("NBA")
root.setAttribute('name', u'季后赛球队')
doc.appendChild(root)
east = doc.createElement("eastteams")
east.setAttribute('name', u'东部球队排名')
No1 = doc.createElement('No.1')
No1.appendChild(doc.createTextNode(u"凯尔特人"))
No2 = doc.createElement('No.2')
No2.appendChild(doc.createTextNode(u"骑士"))
No3 = doc.createElement('No.3')
No3.appendChild(doc.createTextNode(u"猛龙"))
east.appendChild(No1)
east.appendChild(No2)
east.appendChild(No3)
west = doc.createElement("westteams")
west.setAttribute('name', u'西部球队排名')
No1 = doc.createElement('No.1')
No1.appendChild(doc.createTextNode(u"勇士"))
No2 = doc.createElement('No.2')
No2.appendChild(doc.createTextNode(u"马刺"))
No3 = doc.createElement('No.3')
No3.appendChild(doc.createTextNode(u"火箭"))
west.appendChild(No1)
west.appendChild(No2)
west.appendChild(No3)
root.appendChild(east)
root.appendChild(west)
print doc.toxml()
fp = codecs.open('e:\\nba.xml', 'w', 'utf-8')
doc.writexml(fp, indent='', addindent='\t', newl='\n', encoding="utf-8")
fp.close()